version: '2'

services:
  templates:
    image: portainer/templates
    container_name: "portainer-templates"
    restart: unless-stopped
    networks:
      - local

  portainer:
    image: portainer/portainer
    container_name: "portainer"
    restart: unless-stopped
    ports:
      - "9000:9000"
    command: --templates http://templates/templates.json
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  watchtower:
    image: v2tec/watchtower
    container_name: "watchtower"
    restart: unless-stopped
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  local:
    driver: bridge

volumes:
  portainer_data:
    external: true
